#相机参数
/**:
  ros__parameters:
    image_width: 1440
    image_height: 1080
    fov_h: 57.7 #87.7
    fov_v: 56.7
    new_fov_h: 27 #67
    new_fov_v: 40.9
    usb_frame_rate: 120
    usb_exposure: 8000 #1-80000______250
    usb_gamma: 160
    usb_gain: 10 #0-96

    use_roi: false
    imshow: true
