{
   "Hikvision1280_1024" : {
        "Prime6mm1" : {
            "Intrinsic" : {
                "rows" : 3,
                "cols" : 3,
                "channel" : 1,
                "data" : [1638.61964722422, 0,              663.942481914920,
                          0,              1639.46122625732, 663.942481914920,
                          0,              0,              1.0000         ]
            },
            "Distortion" : {
                "rows" : 5,
                "cols" : 1,
                "channel" : 1,
                "data" : [-0.0544334113093420, 0.367781317551849, -0.00687686410781571, -0.00687686410781571, -1.40932362491381]
            }

        },
        "Prime6mm2" : {
            "Intrinsic" : {
                "rows" : 3,
                "cols" : 3,
                "channel" : 1,
                "data" : [1638.61964722422, 0,              663.942481914920,
                          0,              1639.46122625732, 663.942481914920,
                          0,              0,              1.0000         ]
            },
            "Distortion" : {
                "rows" : 5,
                "cols" : 1,
                "channel" : 1,
                "data" : [-0.0544334113093420, 0.367781317551849, -0.00687686410781571, -0.00687686410781571, -1.40932362491381]
            }

        },
         "Prime6mm3" : {
            "Intrinsic" : {
                "rows" : 3,
                "cols" : 3,
                "channel" : 1,
                "data" : [1638.61964722422, 0,              663.942481914920,
                          0,              1639.46122625732, 663.942481914920,
                          0,              0,              1.0000         ]
            },
            "Distortion" : {
                "rows" : 5,
                "cols" : 1,
                "channel" : 1,
                "data" : [-0.0544334113093420, 0.367781317551849, -0.00687686410781571, -0.00687686410781571, -1.40932362491381]
            }

        },
        
       
  }























}

